name: rust-fibbot-action
description: GitHub Action in Rust that scans pull request content for numbers, calculates their Fibonacci numbers, and posts a comment with the results

on:
  workflow_dispatch:
    inputs:
      enable:
        description: a flag to enable Fibonacci calculation
        required: true
        default: 'true'
      limit:
        description: a threshold limit
        required: true
        default: '100'
# runs:
#   using: "composite"
#   steps:
#     - name: Run Rust program
#       run: |
#         cargo run --release --${{ inputs.input1 }} ${{ inputs.input2 }}
