name: rust-fibbot-action
description: GitHub Action in Rust that scans pull request content for numbers, calculates their Fibonacci numbers, and posts a comment with the results

inputs:
  pr_number:
    description: "pulll request number"
    required: true
  enable_fib:
    description: "Enable Fibonacci"
    required: false
    default: "true"
  max_threshold:
    description: "Max threshold"
    required: false
    default: "100"
  github_token:
    description: "GitHub token to interact with GitHub API"
    required: true


runs:
  using: "composite"
  steps:
    - name: Build FibBot
      run: cargo build --release
      shell: bash
    - name: Run FibBot
      run: |
        export PR_NUMBER="${{ inputs.pr_number }}"
        cargo run "${{ inputs.enable_fib }}" "${{ inputs.max_threshold }}"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
