name: Minimal Action Implementation
on:
  push:
  pull_request_target:
    types: [opened, synchronize]
permissions:
  pull-requests: write
  contents: read
  issues: write
  
  

jobs:
  fibonacci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable #specifies the latest rust version to install

      - name: Run FibBot
        uses: Franck-Sorel/fibbot@master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          LIMIT: ${{ secrets.LIMIT }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          
          
        with:
          enable_fib: "true"
        
