name: Minimal Action Implementation

on:
  pull_request:
    types: [opened, synchronize]
    inputs:
      enable:
        description: a flag to enable Fibonacci calculation
        required: true
        default: 'true'
      limit:
        description: a threshold limit
        required: true
        default: '100'
  push:
    branches:
      - test
      - master

jobs:
  fibonacci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable #specifies the latest rust version to install

      - name: Build the project
        run: cargo build --release

      - name: Run the bot
        run: ./target/release/fibonacci_number ${{ github.event.inputs.enable }} ${{ github.event.inputs.limit }}
